name: PR Validation

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install htmlhint stylelint parcel
      - name: Lint HTML
        run: npx htmlhint "src/**/*.html"
      - name: Lint CSS
        run: npx stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install parcel
      - name: Build site
        run: npx parcel build src/index.html --no-optimize --dist-dir build
